# whole image model
#python dme_explainable.py --weight /home/weidong/code/github/mask_rcnn_pytorch/paper_data/output/emei_od_and_fovea_detection_train_20171114113745_rsn34_od_and_fovea_detection/emei_od_and_fovea_detection_rsn34_02164_best.pth --phase test --weight_seg /home/weidong/code/dr/RetinalImagesVesselExtraction/task/output/common_lesions_segmentaion_train_20171114173605_unet_whole_images_ex/common_segmentation_unet_1634_best.pth --model_seg unet

# patch model
python dme_explainable.py --weight /home/weidong/code/github/mask_rcnn_pytorch/paper_data/output/emei_od_and_fovea_detection_train_20171114113745_rsn34_od_and_fovea_detection/emei_od_and_fovea_detection_rsn34_02164_best.pth --phase test --weight_seg /home/weidong/code/dr/RetinalImagesVesselExtraction/task/output/common_lesions_segmentaion_train_20171114155158_unet_ex_patches/common_segmentation_unet_1528_best.pth --model_seg unet
